/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Vincent Yanez (https://sketchfab.com/vinceyanez)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/minecraft-steve-cb228dcc137042cc9a3dc588758cc6e9
title: Minecraft - Steve
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('mod/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, -4]}>
              <mesh geometry={nodes['Steve_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('mod/scene.gltf')
